name: Yarn PR

on:
  push:
    branches: [master]
  schedule:
    - cron: "0 1 * * *"

jobs:
  build:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Yarn Install
        run: yarn
      - name: Run Script
        run: yarn start
        env:
          CI: true
